In [21]:
import numpy as np
import pandas as pd

In [22]:
movies = pd.read_csv("/100_Days_of_ml/Hybrid_Movie_Recommendation_System/data/tmdb_5000_movies.csv")
credits = pd.read_csv("/100_Days_of_ml/Hybrid_Movie_Recommendation_System/data/tmdb_5000_credits.csv")

In [23]:
movies = movies[
    [
        'id',
        'title',
        'overview',
        'genres',
        'keywords'
    ]
]

credits = credits[
    [
        'movie_id',
        'cast',
        'crew'
    ]
]

In [24]:
movies = movies.merge(
    credits,
    left_on="id",
    right_on="movie_id"
)

In [25]:
movies.drop(
    "movie_id",
    axis=1,
    inplace=True
)

In [26]:
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [27]:
movies.dropna(inplace = True)

In [28]:
import ast

In [29]:
movies["genres"] = movies["genres"].apply(ast.literal_eval)

In [30]:
type(movies.iloc[0].genres)

list

In [31]:
movies.iloc[0].genres

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [32]:
movies["keywords"] = movies["keywords"].apply(ast.literal_eval)

movies["cast"] = movies["cast"].apply(ast.literal_eval)

movies["crew"] = movies["crew"].apply(ast.literal_eval)

In [33]:
print(type(movies.iloc[0].keywords))
print(type(movies.iloc[0].cast))
print(type(movies.iloc[0].crew))

<class 'list'>
<class 'list'>
<class 'list'>

In [34]:
## this is the function used to convert we have to extract only names in movies["genres"]

def converrt(obj):
    L = []

    for i in obj:
        L.append(i["name"])

    return L

In [35]:
movies["genres"] = movies["genres"].apply(converrt)

In [36]:
movies.iloc[0]["genres"]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [37]:
movies["keywords"] = movies["keywords"].apply(converrt)

### Function For Extraction only 3 top(lead) Actors Of Any Movie

In [38]:
def Fetch_Cast(obj):
    L = []
    counter = 0
    for i in obj:
        if counter != 3:
            L.append(i["name"])
            counter += 1

        else:
            break
    return L

In [39]:
movies["cast"] = movies["cast"].apply(Fetch_Cast)

In [40]:
movies.iloc[2]["cast"]

['Daniel Craig', 'Christoph Waltz', 'Léa Seydoux']

### Extract Director From Crew

In [41]:
def fetch_director(obj):

    L = []

    for i in obj:

        if i["job"] == "Director":
            L.append(i["name"])
            break

    return L

In [42]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [43]:
movies.iloc[1]["crew"]

['Gore Verbinski']

## Remove Spaces

In [44]:
def RemoveSpaces(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [45]:
movies["genres"] = movies["genres"].apply(RemoveSpaces)
movies["keywords"] = movies["keywords"].apply(RemoveSpaces)
movies["cast"] = movies["cast"].apply(RemoveSpaces)
movies["crew"] = movies["crew"].apply(RemoveSpaces)

In [46]:
movies.iloc[0]

id                                                      19995
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
genres           [Action, Adventure, Fantasy, ScienceFiction]
keywords    [cultureclash, future, spacewar, spacecolony, ...
cast            [SamWorthington, ZoeSaldana, SigourneyWeaver]
crew                                           [JamesCameron]
Name: 0, dtype: object

### Creating Tags

In [47]:
movies["overview"] = movies["overview"].apply(lambda x:x.split())

In [48]:
movies.iloc[0]["overview"]
type(movies.iloc[0]["overview"])

list

In [49]:
movies["tags"] = movies["overview"] + \
                 movies["genres"] + \
                 movies["keywords"] + \
                 movies["cast"] + \
                 movies["crew"]

In [50]:
movies.iloc[20]["tags"]

['Peter',
 'Parker',
 'is',
 'an',
 'outcast',
 'high',
 'schooler',
 'abandoned',
 'by',
 'his',
 'parents',
 'as',
 'a',
 'boy,',
 'leaving',
 'him',
 'to',
 'be',
 'raised',
 'by',
 'his',
 'Uncle',
 'Ben',
 'and',
 'Aunt',
 'May.',
 'Like',
 'most',
 'teenagers,',
 'Peter',
 'is',
 'trying',
 'to',
 'figure',
 'out',
 'who',
 'he',
 'is',
 'and',
 'how',
 'he',
 'got',
 'to',
 'be',
 'the',
 'person',
 'he',
 'is',
 'today.',
 'As',
 'Peter',
 'discovers',
 'a',
 'mysterious',
 'briefcase',
 'that',
 'belonged',
 'to',
 'his',
 'father,',
 'he',
 'begins',
 'a',
 'quest',
 'to',
 'understand',
 'his',
 "parents'",
 'disappearance',
 '–',
 'leading',
 'him',
 'directly',
 'to',
 'Oscorp',
 'and',
 'the',
 'lab',
 'of',
 'Dr.',
 'Curt',
 'Connors,',
 'his',
 "father's",
 'former',
 'partner.',
 'As',
 'Spider-Man',
 'is',
 'set',
 'on',
 'a',
 'collision',
 'course',
 'with',
 "Connors'",
 'alter',
 'ego,',
 'The',
 'Lizard,',
 'Peter',
 'will',
 'make',
 'life-altering',
 'choices',
 'to',
 'use',
 'his',
 'powers',
 'and',
 'shape',
 'his',
 'destiny',
 'to',
 'become',
 'a',
 'hero.',
 'Action',
 'Adventure',
 'Fantasy',
 'lossoffather',
 'vigilante',
 'serum',
 'marvelcomic',
 'scientificexperiment',
 'spiderbite',
 'maskedvigilante',
 'reboot',
 'superpowers',
 'geneticengineering',
 'socialoutcast',
 'duringcreditsstinger',
 'AndrewGarfield',
 'EmmaStone',
 'RhysIfans',
 'MarcWebb']

In [51]:
# We keep Only These Columns
    # id → useful for fetching movie details or posters.
    # title → user searches by movie title.
    # tags → used to calculate movie similarity.

movies = movies[
    [
        "id",
        "title",
        "tags"
    ]
]

In [52]:
movies.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [53]:
movies["tags"] = movies["tags"].apply(lambda x:" ".join(x))

In [54]:
movies.iloc[0]["tags"]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [55]:
movies["tags"] = movies["tags"].apply(lambda x: x.lower())

In [56]:
from nltk.stem.porter import PorterStemmer

In [57]:
ps = PorterStemmer()

In [58]:
print(ps.stem("loving"))
print(ps.stem("travelling"))

love
travel

### Writing Function For Stemming

In [59]:
# action adventure sciencefiction ->>> before split
# Action
# Adventure ->> After Split
# sciencefiction  
 
def stem(text):
    y = [] 
    for i in text.split(): # split texts 
        y.append(ps.stem(i)) # Check For all Text One by one  
    return " ".join(y) # again convert to sentence

In [60]:
movies["tags"]  = movies["tags"].apply(stem)

In [61]:
movies.iloc[0]["tags"]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [63]:
movies.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [64]:
movies.to_csv("/100_Days_of_ml/Hybrid_Movie_Recommendation_System/data/final_movies.csv", index=False)