In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("/100_Days_of_ml/Hybrid_Movie_Recommendation_System/data/final_movies.csv")

In [3]:
movies.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [4]:
movies.shape

(4800, 3)

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4800 non-null   int64
 1   title   4800 non-null   object
 2   tags    4800 non-null   object
dtypes: int64(1), object(2)
memory usage: 112.6+ KB

# Content Based Recommendation System

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words="english")

In [7]:
vectors = cv.fit_transform(movies["tags"]).toarray()

In [8]:
vectors.shape

(4800, 5000)

In [9]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4800, 5000))

In [10]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [11]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [12]:
np.count_nonzero(vectors[0])

np.int64(31)

In [13]:
vectors[0][:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0])

## Match Words TO Columns

In [14]:
cv.get_feature_names_out()[:20]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '18thcenturi', '19', '1910', '1920',
       '1930', '1940'], dtype=object)

In [15]:
words = cv.get_feature_names_out()

for i in range(len(words)):
    if vectors[0][i] > 0:
        print(words[i], ":", vectors[0][i])

3d : 1
action : 1
adventur : 1
alien : 2
alienplanet : 1
battl : 1
becom : 1
century : 1
cultureclash : 1
dispatch : 1
fantasi : 1
follow : 1
futur : 1
futurist : 1
jamescameron : 1
marin : 2
mission : 1
moon : 1
order : 1
protect : 1
romanc : 1
sciencefict : 1
sigourneyweav : 1
societi : 1
soldier : 1
space : 1
spacetravel : 1
torn : 1
tribe : 1
uniqu : 1
zoesaldana : 1

In [16]:
vectors[0][:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0])

# Cosine Similarity

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [18]:
similarity[0]

array([1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ], shape=(4800,))

In [20]:
print(similarity[0][0])

0.9999999999999998

In [21]:
similarity[0][1]

np.float64(0.08458258116519013)

In [22]:
movies[movies["title"]=="Avatar"]

      id   title                                               tags
0  19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [25]:
print(movies[movies["title"]=="Avatar"].index[0])

0

In [31]:
movie_index = movies[movies["title"]=="Avatar"].index[0]

In [32]:
print(movie_index)

0

In [33]:
similarity[movie_index]

array([1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ], shape=(4800,))

In [34]:
distances = similarity[movie_index]

### Enumerate

In [28]:
numbers = [10,20,30]
for item in enumerate(numbers):
    print(item)

(0, 10)
(1, 20)
(2, 30)

In [35]:
list(enumerate(distances))

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.08458258116519013)),
 (2, np.float64(0.08718572905786445)),
 (3, np.float64(0.074458079104994)),
 (4, np.float64(0.19184045508446734)),
 (5, np.float64(0.1098436937909367)),
 (6, np.float64(0.04078236951430929)),
 (7, np.float64(0.1487044791289829)),
 (8, np.float64(0.06003002251876642)),
 (9, np.float64(0.09802861627917438)),
 (10, np.float64(0.10397504898200727)),
 (11, np.float64(0.09592022754223367)),
 (12, np.float64(0.09158437663089952)),
 (13, np.float64(0.04559607525875532)),
 (14, np.float64(0.12996881122750908)),
 (15, np.float64(0.06367145399670132)),
 (16, np.float64(0.08000711205939975)),
 (17, np.float64(0.14273829330008253)),
 (18, np.float64(0.09620723036050562)),
 (19, np.float64(0.08419653359482289)),
 (20, np.float64(0.05881716976750462)),
 (21, np.float64(0.11277677488692017)),
 (22, np.float64(0.06711560552140244)),
 (23, np.float64(0.0885807893036239)),
 (24, np.float64(0.05405405405405406)),
 (25, np.float64(0.05170108966939356)),
 (26, np.float64(0.1559625734730109)),
 (27, np.float64(0.195976600339204)),
 (28, np.float64(0.11810771907149853)),
 (29, np.float64(0.06590621627456203)),
 (30, np.float64(0.06774581282657174)),
 (31, np.float64(0.16120647005479025)),
 (32, np.float64(0.0863465783552691)),
 (33, np.float64(0.09863939238321438)),
 (34, np.float64(0.0)),
 (35, np.float64(0.10067340828210367)),
 (36, np.float64(0.17348855898381338)),
 (37, np.float64(0.08000711205939975)),
 (38, np.float64(0.08219949365267865)),
 (39, np.float64(0.08336550215650926)),
 (40, np.float64(0.07798128673650545)),
 (41, np.float64(0.1678603981989089)),
 (42, np.float64(0.0)),
 (43, np.float64(0.09208185110322616)),
 (44, np.float64(0.03427955850955305)),
 (45, np.float64(0.08351476906593233)),
 (46, np.float64(0.14097096860865022)),
 (47, np.float64(0.199363055707225)),
 (48, np.float64(0.08561170049453902)),
 (49, np.float64(0.06003002251876642)),
 (50, np.float64(0.1144727614064285)),
 (51, np.float64(0.08094446585163528)),
 (52, np.float64(0.1487044791289829)),
 (53, np.float64(0.04355035563093422)),
 (54, np.float64(0.03163859985841663)),
 (55, np.float64(0.07306621658015879)),
 (56, np.float64(0.14019992744655632)),
 (57, np.float64(0.024507154069793594)),
 (58, np.float64(0.06839411288813299)),
 (59, np.float64(0.07352146220938077)),
 (60, np.float64(0.0186145197762485)),
 (61, np.float64(0.23490461932490855)),
 (62, np.float64(0.08489527199560176)),
 (63, np.float64(0.08284930213349333)),
 (64, np.float64(0.03001501125938321)),
 (65, np.float64(0.01979131233319198)),
 (66, np.float64(0.02279803762937766)),
 (67, np.float64(0.16439898730535726)),
 (68, np.float64(0.1221125021745327)),
 (69, np.float64(0.026846242208560973)),
 (70, np.float64(0.07702442489446452)),
 (71, np.float64(0.07435223956449145)),
 (72, np.float64(0.1389425035941821)),
 (73, np.float64(0.03355780276070122)),
 (74, np.float64(0.20518233866439894)),
 (75, np.float64(0.10529962529853128)),
 (76, np.float64(0.07271792483455794)),
 (77, np.float64(0.014588051152682587)),
 (78, np.float64(0.05134961659630968)),
 (79, np.float64(0.06314740019611717)),
 (80, np.float64(0.05114214254947678)),
 (81, np.float64(0.11168711865749101)),
 (82, np.float64(0.07702442489446452)),
 (83, np.float64(0.1823843010350213)),
 (84, np.float64(0.12527215359889848)),
 (85, np.float64(0.11565903932254226)),
 (86, np.float64(0.07194017065667525)),
 (87, np.float64(0.11277677488692017)),
 (88, np.float64(0.09158437663089954)),
 (89, np.float64(0.058352204610730346)),
 (90, np.float64(0.06213697660012)),
 (91, np.float64(0.16916516233038026)),
 (92, np.float64(0.06314740019611717)),
 (93, np.float64(0.07194017065667525)),
 (94, np.float64(0.1898315991504998)),
 (95, np.float64(0.14237369936287486)),
 (96, np.float64(0.07798128673650545)),
 (97, np.float64(0.07045670884515312)),
 (98, np.float64(0.07610194341477616)),
 (99, np.float64(0.02702702702702703)),
 (100, np.float64(0.0685591170191061)),
 (101, np.float64(0.07798128673650545)),
 (102, np.float64(0.12629480039223434)),
 (103, np.float64(0.08094446585163528)),
 (104, np.float64(0.056388387443460086)),
 (105, np.float64(0.10514994558491725)),
 (106, np.float64(0.06314740019611717)),
 (107, np.float64(0.06263607679944924)),
 (108, np.float64(0.14704292441876157)),
 (109, np.float64(0.06575959492214292)),
 (110, np.float64(0.04559607525875532)),
 (111, np.float64(0.1522038868295523)),
 (112, np.float64(0.07798128673650545)),
 (113, np.float64(0.04393747751637468)),
 (114, np.float64(0.04649905549752771)),
 (115, np.float64(0.04433510985214727)),
 (116, np.float64(0.048478616556371965)),
 (117, np.float64(0.06003002251876642)),
 (118, np.float64(0.034094761699651185)),
 (119, np.float64(0.04393747751637468)),
 (120, np.float64(0.0)),
 (121, np.float64(0.11277677488692017)),
 (122, np.float64(0.11810771907149853)),
 (123, np.float64(0.1139901881468883)),
 (124, np.float64(0.06839411288813299)),
 (125, np.float64(0.07948588753990432)),
 (126, np.float64(0.13513513513513514)),
 (127, np.float64(0.14797064923339878)),
 (128, np.float64(0.0)),
 (129, np.float64(0.09394227846020416)),
 (130, np.float64(0.027399831217559546)),
 (131, np.float64(0.106676149412533)),
 (132, np.float64(0.04559607525875532)),
 (133, np.float64(0.028618190351607124)),
 (134, np.float64(0.13151918984428584)),
 (135, np.float64(0.0)),
 (136, np.float64(0.023728949893812478)),
 (137, np.float64(0.030528125543633176)),
 (138, np.float64(0.12996881122750908)),
 (139, np.float64(0.12234710854292788)),
 (140, np.float64(0.04559607525875532)),
 (141, np.float64(0.0885807893036239)),
 (142, np.float64(0.08585457105482137)),
 (143, np.float64(0.08787495503274936)),
 (144, np.float64(0.050734628943184104)),
 (145, np.float64(0.019510570275964215)),
 (146, np.float64(0.01643989873053573)),
 (147, np.float64(0.056388387443460086)),
 (148, np.float64(0.09863939238321438)),
 (149, np.float64(0.15719549837837185)),
 (150, np.float64(0.16646698038757363)),
 (151, np.float64(0.2056773510573183)),
 (152, np.float64(0.08458258116519013)),
 (153, np.float64(0.07974522228289)),
 (154, np.float64(0.06213697660012)),
 (155, np.float64(0.020712325533373332)),
 (156, np.float64(0.06070834938872646)),
 (157, np.float64(0.10067340828210367)),
 (158, np.float64(0.13549162565314346)),
 (159, np.float64(0.0644825880219161)),
 (160, np.float64(0.11869522585912262)),
 (161, np.float64(0.03224129401095805)),
 (162, np.float64(0.03355780276070122)),
 (163, np.float64(0.05134961659630968)),
 (164, np.float64(0.08108108108108109)),
 (165, np.float64(0.04649905549752771)),
 (166, np.float64(0.12683657235796025)),
 (167, np.float64(0.09158437663089954)),
 (168, np.float64(0.17757120130114434)),
 (169, np.float64(0.08948747402853657)),
 (170, np.float64(0.10793322294408637)),
 (171, np.float64(0.02302046277580654)),
 (172, np.float64(0.21524880100025257)),
 (173, np.float64(0.02348556961505104)),
 (174, np.float64(0.07897471897389846)),
 (175, np.float64(0.07194017065667525)),
 (176, np.float64(0.029526929767874632)),
 (177, np.float64(0.0)),
 (178, np.float64(0.024784079854830485)),
 (179, np.float64(0.07352146220938077)),
 (180, np.float64(0.022371868507134143)),
 (181, np.float64(0.04559607525875532)),
 (182, np.float64(0.1186447494690624)),
 (183, np.float64(0.0713262951621492)),
 (184, np.float64(0.17757120130114434)),
 (185, np.float64(0.05134961659630968)),
 (186, np.float64(0.059808916712167495)),
 (187, np.float64(0.1559625734730109)),
 (188, np.float64(0.022371868507134143)),
 (189, np.float64(0.1162476387438193)),
 (190, np.float64(0.08561170049453902)),
 (191, np.float64(0.04956815970966097)),
 (192, np.float64(0.047960113771116836)),
 (193, np.float64(0.07983920607777244)),
 (194, np.float64(0.0)),
 (195, np.float64(0.06003002251876642)),
 (196, np.float64(0.05264981264926564)),
 (197, np.float64(0.037470006725398436)),
 (198, np.float64(0.058123819371909635)),
 (199, np.float64(0.08787495503274936)),
 (200, np.float64(0.11028219331407116)),
 (201, np.float64(0.0)),
 (202, np.float64(0.03163859985841663)),
 (203, np.float64(0.08458258116519013)),
 (204, np.float64(0.050141221056390024)),
 (205, np.float64(0.07543142864047142)),
 (206, np.float64(0.11241002017619531)),
 (207, np.float64(0.07798128673650545)),
 (208, np.float64(0.12427395320024)),
 (209, np.float64(0.0685591170191061)),
 (210, np.float64(0.07610194341477616)),
 (211, np.float64(0.024784079854830485)),
 (212, np.float64(0.06711560552140243)),
 (213, np.float64(0.059808916712167495)),
 (214, np.float64(0.0)),
 (215, np.float64(0.06711560552140243)),
 (216, np.float64(0.06575959492214292)),
 (217, np.float64(0.0863465783552691)),
 (218, np.float64(0.03874921291460643)),
 (219, np.float64(0.09320546490018)),
 (220, np.float64(0.18009006755629928)),
 (221, np.float64(0.047960113771116836)),
 (222, np.float64(0.08094446585163528)),
 (223, np.float64(0.10529962529853128)),
 (224, np.float64(0.061649620239508984)),
 (225, np.float64(0.047457899787624956)),
 (226, np.float64(0.030528125543633176)),
 (227, np.float64(0.08336550215650926)),
 (228, np.float64(0.11185934253567072)),
 (229, np.float64(0.10892898631973956)),
 (230, np.float64(0.0930725988812425)),
 (231, np.float64(0.0)),
 (232, np.float64(0.11277677488692017)),
 (233, np.float64(0.10514994558491725)),
 (234, np.float64(0.08710071126186844)),
 (235, np.float64(0.07702442489446452)),
 (236, np.float64(0.11624763874381927)),
 (237, np.float64(0.06711560552140244)),
 (238, np.float64(0.11241002017619531)),
 (239, np.float64(0.09248165577087425)),
 (240, np.float64(0.047457899787624956)),
 (241, np.float64(0.08000711205939975)),
 (242, np.float64(0.08219949365267865)),
 (243, np.float64(0.09394227846020416)),
 (244, np.float64(0.09320546490018)),
 (245, np.float64(0.08219949365267865)),
 (246, np.float64(0.07696578428840449)),
 (247, np.float64(0.0)),
 (248, np.float64(0.04516387521771449)),
 (249, np.float64(0.14019992744655632)),
 (250, np.float64(0.0)),
 (251, np.float64(0.04244763599780088)),
 (252, np.float64(0.02054987341316966)),
 (253, np.float64(0.06367145399670132)),
 (254, np.float64(0.07045670884515312)),
 (255, np.float64(0.0)),
 (256, np.float64(0.11314714296070713)),
 (257, np.float64(0.05405405405405406)),
 (258, np.float64(0.01793740008335438)),
 (259, np.float64(0.06213697660012)),
 (260, np.float64(0.20668850837512243)),
 (261, np.float64(0.024507154069793594)),
 (262, np.float64(0.10793322294408637)),
 (263, np.float64(0.09863939238321438)),
 (264, np.float64(0.0)),
 (265, np.float64(0.027788500718836418)),
 (266, np.float64(0.10028244211278005)),
 (267, np.float64(0.06575959492214292)),
 (268, np.float64(0.0533380747062665)),
 (269, np.float64(0.03001501125938321)),
 (270, np.float64(0.08948747402853657)),
 (271, np.float64(0.07194017065667525)),
 (272, np.float64(0.028194193721730043)),
 (273, np.float64(0.021402925123634755)),
 (274, np.float64(0.09097816785925636)),
 (275, np.float64(0.1453095484297741)),
 (276, np.float64(0.06327719971683327)),
 (277, np.float64(0.05381220025006314)),
 (278, np.float64(0.1186447494690624)),
 (279, np.float64(0.09394227846020416)),
 (280, np.float64(0.0)),
 (281, np.float64(0.06590621627456203)),
 (282, np.float64(0.04516387521771449)),
 (283, np.float64(0.027788500718836418)),
 (284, np.float64(0.0186145197762485)),
 (285, np.float64(0.01979131233319198)),
 (286, np.float64(0.07916524933276792)),
 (287, np.float64(0.02632490632463282)),
 (288, np.float64(0.027788500718836418)),
 (289, np.float64(0.04649905549752771)),
 (290, np.float64(0.06327719971683327)),
 (291, np.float64(0.050141221056390024)),
 (292, np.float64(0.09004503377814962)),
 (293, np.float64(0.03001501125938321)),
 (294, np.float64(0.1453095484297741)),
 (295, np.float64(0.106676149412533)),
 (296, np.float64(0.03929887459459296)),
 (297, np.float64(0.04474373701426829)),
 (298, np.float64(0.0)),
 (299, np.float64(0.06025359879550432)),
 (300, np.float64(0.17348855898381338)),
 (301, np.float64(0.09491579957524988)),
 (302, np.float64(0.07045670884515312)),
 (303, np.float64(0.028194193721730043)),
 (304, np.float64(0.06667259338283313)),
 (305, np.float64(0.1926263261127128)),
 (306, np.float64(0.08219949365267865)),
 (307, np.float64(0.11022596991336672)),
 (308, np.float64(0.0685591170191061)),
 (309, np.float64(0.06327719971683327)),
 (310, np.float64(0.03106848830006)),
 (311, np.float64(0.1522038868295523)),
 (312, np.float64(0.10146925788636821)),
 (313, np.float64(0.055577001437672836)),
 (314, np.float64(0.0)),
 (315, np.float64(0.08458258116519013)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.10067340828210367)),
 (320, np.float64(0.03106848830006)),
 (321, np.float64(0.0)),
 (322, np.float64(0.213352298825066)),
 (323, np.float64(0.03001501125938321)),
 (324, np.float64(0.024507154069793594)),
 (325, np.float64(0.10067340828210367)),
 (326, np.float64(0.05723638070321425)),
 (327, np.float64(0.027788500718836418)),
 (328, np.float64(0.027788500718836418)),
 (329, np.float64(0.08000711205939975)),
 (330, np.float64(0.10146925788636821)),
 (331, np.float64(0.09119215051751065)),
 (332, np.float64(0.10810810810810811)),
 (333, np.float64(0.024784079854830485)),
 (334, np.float64(0.09802861627917438)),
 (335, np.float64(0.04697113923010208)),
 (336, np.float64(0.07009996372327816)),
 (337, np.float64(0.04604092555161308)),
 (338, np.float64(0.0)),
 (339, np.float64(0.04956815970966097)),
 (340, np.float64(0.050141221056390024)),
 (341, np.float64(0.08336550215650926)),
 (342, np.float64(0.1633934794796094)),
 (343, np.float64(0.019510570275964215)),
 (344, np.float64(0.03001501125938321)),
 (345, np.float64(0.023249527748763855)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06213697660012)),
 (349, np.float64(0.07702442489446452)),
 (350, np.float64(0.04956815970966097)),
 (351, np.float64(0.0)),
 (352, np.float64(0.027788500718836418)),
 (353, np.float64(0.041757384532966166)),
 (354, np.float64(0.02196873875818734)),
 (355, np.float64(0.036992662308349696)),
 (356, np.float64(0.09158437663089952)),
 (357, np.float64(0.0)),
 (358, np.float64(0.06105625108726635)),
 (359, np.float64(0.03163859985841663)),
 (360, np.float64(0.02122381799890044)),
 (361, np.float64(0.07610194341477616)),
 (362, np.float64(0.09672388203287416)),
 (363, np.float64(0.10042266465917388)),
 (364, np.float64(0.023728949893812478)),
 (365, np.float64(0.07610194341477616)),
 (366, np.float64(0.05723638070321425)),
 (367, np.float64(0.0)),
 (368, np.float64(0.13151918984428584)),
 (369, np.float64(0.08108108108108109)),
 (370, np.float64(0.05134961659630968)),
 (371, np.float64(0.09695723311274393)),
 (372, np.float64(0.047960113771116836)),
 (373, np.float64(0.1752499093081954)),
 (374, np.float64(0.038482892144202245)),
 (375, np.float64(0.06213697660011999)),
 (376, np.float64(0.047457899787624956)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.05141933776432957)),
 (380, np.float64(0.05264981264926564)),
 (381, np.float64(0.08489527199560176)),
 (382, np.float64(0.0)),
 (383, np.float64(0.04393747751637468)),
 (384, np.float64(0.029061909685954818)),
 (385, np.float64(0.0)),
 (386, np.float64(0.022167554926073633)),
 (387, np.float64(0.023980056885558418)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0885807893036239)),
 (390, np.float64(0.02666903735313325)),
 (391, np.float64(0.05733298225836872)),
 (392, np.float64(0.030528125543633176)),
 (393, np.float64(0.0)),
 (394, np.float64(0.025070610528195012)),
 (395, np.float64(0.05264981264926564)),
 (396, np.float64(0.04433510985214727)),
 (397, np.float64(0.05264981264926564)),
 (398, np.float64(0.0)),
 (399, np.float64(0.023980056885558418)),
 (400, np.float64(0.09158437663089952)),
 (401, np.float64(0.03106848830006)),
 (402, np.float64(0.07897471897389846)),
 (403, np.float64(0.08419653359482289)),
 (404, np.float64(0.06213697660012)),
 (405, np.float64(0.056388387443460086)),
 (406, np.float64(0.021049133398705722)),
 (407, np.float64(0.021586644588817275)),
 (408, np.float64(0.03287979746107146)),
 (409, np.float64(0.0)),
 (410, np.float64(0.09913631941932194)),
 (411, np.float64(0.0533380747062665)),
 (412, np.float64(0.09695723311274393)),
 (413, np.float64(0.14309095175803563)),
 (414, np.float64(0.03001501125938321)),
 (415, np.float64(0.05413539955388112)),
 (416, np.float64(0.05134961659630968)),
 (417, np.float64(0.03287979746107146)),
 (418, np.float64(0.03587480016670876)),
 (419, np.float64(0.06974858324629157)),
 (420, np.float64(0.1139901881468883)),
 (421, np.float64(0.02348556961505104)),
 (422, np.float64(0.11810771907149853)),
 (423, np.float64(0.041757384532966166)),
 (424, np.float64(0.037470006725398436)),
 (425, np.float64(0.06475993376645182)),
 (426, np.float64(0.05446449315986979)),
 (427, np.float64(0.02666903735313325)),
 (428, np.float64(0.056573571480353566)),
 (429, np.float64(0.0)),
 (430, np.float64(0.05134961659630968)),
 (431, np.float64(0.024507154069793594)),
 (432, np.float64(0.11510231387903269)),
 (433, np.float64(0.03163859985841663)),
 (434, np.float64(0.0)),
 (435, np.float64(0.03587480016670876)),
 (436, np.float64(0.0)),
 (437, np.float64(0.025993762245501817)),
 (438, np.float64(0.12392039927415242)),
 (439, np.float64(0.02666903735313325)),
 (440, np.float64(0.025070610528195012)),
 (441, np.float64(0.058123819371909635)),
 (442, np.float64(0.04604092555161308)),
 (443, np.float64(0.06475993376645182)),
 (444, np.float64(0.0)),
 (445, np.float64(0.10028244211278005)),
 (446, np.float64(0.02348556961505104)),
 (447, np.float64(0.06532553344640132)),
 (448, np.float64(0.021586644588817275)),
 (449, np.float64(0.11115400287534567)),
 (450, np.float64(0.021586644588817275)),
 (451, np.float64(0.025367314471592052)),
 (452, np.float64(0.03106848830006)),
 (453, np.float64(0.024784079854830485)),
 (454, np.float64(0.11742784807525519)),
 (455, np.float64(0.061649620239508984)),
 (456, np.float64(0.04393747751637468)),
 (457, np.float64(0.08718572905786445)),
 (458, np.float64(0.04393747751637468)),
 (459, np.float64(0.03504998186163908)),
 (460, np.float64(0.024507154069793594)),
 (461, np.float64(0.14309095175803563)),
 (462, np.float64(0.03271662128033808)),
 (463, np.float64(0.03287979746107146)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.14704292441876154)),
 (467, np.float64(0.10701462561817378)),
 (468, np.float64(0.028194193721730043)),
 (469, np.float64(0.06025359879550432)),
 (470, np.float64(0.04604092555161308)),
 (471, np.float64(0.06475993376645182)),
 (472, np.float64(0.10810810810810811)),
 (473, np.float64(0.09394227846020416)),
 (474, np.float64(0.0)),
 (475, np.float64(0.04433510985214727)),
 (476, np.float64(0.1371182340382122)),
 (477, np.float64(0.0)),
 (478, np.float64(0.05479966243511909)),
 (479, np.float64(0.0891578689526865)),
 (480, np.float64(0.09913631941932194)),
 (481, np.float64(0.0)),
 (482, np.float64(0.022167554926073633)),
 (483, np.float64(0.12655439943366653)),
 (484, np.float64(0.029526929767874632)),
 (485, np.float64(0.0533380747062665)),
 (486, np.float64(0.08099356774626426)),
 (487, np.float64(0.1289651760438322)),
 (488, np.float64(0.06746792083200746)),
 (489, np.float64(0.0)),
 (490, np.float64(0.14349920066683505)),
 (491, np.float64(0.10042266465917388)),
 (492, np.float64(0.07702442489446452)),
 (493, np.float64(0.03106848830006)),
 (494, np.float64(0.0)),
 (495, np.float64(0.19344776406574832)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0685591170191061)),
 (499, np.float64(0.0)),
 (500, np.float64(0.02632490632463282)),
 (501, np.float64(0.08284930213349333)),
 (502, np.float64(0.13549162565314346)),
 (503, np.float64(0.07610194341477615)),
 (504, np.float64(0.0)),
 (505, np.float64(0.1371182340382122)),
 (506, np.float64(0.03504998186163908)),
 (507, np.float64(0.25903973506580724)),
 (508, np.float64(0.10269923319261937)),
 (509, np.float64(0.022371868507134143)),

In [37]:
movie_list = list(enumerate(distances))
print(movie_list)

[(0, np.float64(0.9999999999999998)), (1, np.float64(0.08458258116519013)), (2, np.float64(0.08718572905786445)), (3, np.float64(0.074458079104994)), (4, np.float64(0.19184045508446734)), (5, np.float64(0.1098436937909367)), (6, np.float64(0.04078236951430929)), (7, np.float64(0.1487044791289829)), (8, np.float64(0.06003002251876642)), (9, np.float64(0.09802861627917438)), (10, np.float64(0.10397504898200727)), (11, np.float64(0.09592022754223367)), (12, np.float64(0.09158437663089952)), (13, np.float64(0.04559607525875532)), (14, np.float64(0.12996881122750908)), (15, np.float64(0.06367145399670132)), (16, np.float64(0.08000711205939975)), (17, np.float64(0.14273829330008253)), (18, np.float64(0.09620723036050562)), (19, np.float64(0.08419653359482289)), (20, np.float64(0.05881716976750462)), (21, np.float64(0.11277677488692017)), (22, np.float64(0.06711560552140244)), (23, np.float64(0.0885807893036239)), (24, np.float64(0.05405405405405406)), (25, np.float64(0.05170108966939356)), (26, np.float64(0.1559625734730109)), (27, np.float64(0.195976600339204)), (28, np.float64(0.11810771907149853)), (29, np.float64(0.06590621627456203)), (30, np.float64(0.06774581282657174)), (31, np.float64(0.16120647005479025)), (32, np.float64(0.0863465783552691)), (33, np.float64(0.09863939238321438)), (34, np.float64(0.0)), (35, np.float64(0.10067340828210367)), (36, np.float64(0.17348855898381338)), (37, np.float64(0.08000711205939975)), (38, np.float64(0.08219949365267865)), (39, np.float64(0.08336550215650926)), (40, np.float64(0.07798128673650545)), (41, np.float64(0.1678603981989089)), (42, np.float64(0.0)), (43, np.float64(0.09208185110322616)), (44, np.float64(0.03427955850955305)), (45, np.float64(0.08351476906593233)), (46, np.float64(0.14097096860865022)), (47, np.float64(0.199363055707225)), (48, np.float64(0.08561170049453902)), (49, np.float64(0.06003002251876642)), (50, np.float64(0.1144727614064285)), (51, np.float64(0.08094446585163528)), (52, np.float64(0.1487044791289829)), (53, np.float64(0.04355035563093422)), (54, np.float64(0.03163859985841663)), (55, np.float64(0.07306621658015879)), (56, np.float64(0.14019992744655632)), (57, np.float64(0.024507154069793594)), (58, np.float64(0.06839411288813299)), (59, np.float64(0.07352146220938077)), (60, np.float64(0.0186145197762485)), (61, np.float64(0.23490461932490855)), (62, np.float64(0.08489527199560176)), (63, np.float64(0.08284930213349333)), (64, np.float64(0.03001501125938321)), (65, np.float64(0.01979131233319198)), (66, np.float64(0.02279803762937766)), (67, np.float64(0.16439898730535726)), (68, np.float64(0.1221125021745327)), (69, np.float64(0.026846242208560973)), (70, np.float64(0.07702442489446452)), (71, np.float64(0.07435223956449145)), (72, np.float64(0.1389425035941821)), (73, np.float64(0.03355780276070122)), (74, np.float64(0.20518233866439894)), (75, np.float64(0.10529962529853128)), (76, np.float64(0.07271792483455794)), (77, np.float64(0.014588051152682587)), (78, np.float64(0.05134961659630968)), (79, np.float64(0.06314740019611717)), (80, np.float64(0.05114214254947678)), (81, np.float64(0.11168711865749101)), (82, np.float64(0.07702442489446452)), (83, np.float64(0.1823843010350213)), (84, np.float64(0.12527215359889848)), (85, np.float64(0.11565903932254226)), (86, np.float64(0.07194017065667525)), (87, np.float64(0.11277677488692017)), (88, np.float64(0.09158437663089954)), (89, np.float64(0.058352204610730346)), (90, np.float64(0.06213697660012)), (91, np.float64(0.16916516233038026)), (92, np.float64(0.06314740019611717)), (93, np.float64(0.07194017065667525)), (94, np.float64(0.1898315991504998)), (95, np.float64(0.14237369936287486)), (96, np.float64(0.07798128673650545)), (97, np.float64(0.07045670884515312)), (98, np.float64(0.07610194341477616)), (99, np.float64(0.02702702702702703)), (100, np.float64(0.0685591170191061)), (101, np.float64(0.07798128673650545)), (102, np.float64(0.12629480039223434)), (103, np.float64(0.08094446585163528)), (104, np.float64(0.056388387443460086)), (105, np.float64(0.10514994558491725)), (106, np.float64(0.06314740019611717)), (107, np.float64(0.06263607679944924)), (108, np.float64(0.14704292441876157)), (109, np.float64(0.06575959492214292)), (110, np.float64(0.04559607525875532)), (111, np.float64(0.1522038868295523)), (112, np.float64(0.07798128673650545)), (113, np.float64(0.04393747751637468)), (114, np.float64(0.04649905549752771)), (115, np.float64(0.04433510985214727)), (116, np.float64(0.048478616556371965)), (117, np.float64(0.06003002251876642)), (118, np.float64(0.034094761699651185)), (119, np.float64(0.04393747751637468)), (120, np.float64(0.0)), (121, np.float64(0.11277677488692017)), (122, np.float64(0.11810771907149853)), (123, np.float64(0.1139901881468883)), (124, np.float64(0.06839411288813299)), (125, np.float64(0.07948588753990432)), (126, np.float64(0.13513513513513514)), (127, np.float64(0.14797064923339878)), (128, np.float64(0.0)), (129, np.float64(0.09394227846020416)), (130, np.float64(0.027399831217559546)), (131, np.float64(0.106676149412533)), (132, np.float64(0.04559607525875532)), (133, np.float64(0.028618190351607124)), (134, np.float64(0.13151918984428584)), (135, np.float64(0.0)), (136, np.float64(0.023728949893812478)), (137, np.float64(0.030528125543633176)), (138, np.float64(0.12996881122750908)), (139, np.float64(0.12234710854292788)), (140, np.float64(0.04559607525875532)), (141, np.float64(0.0885807893036239)), (142, np.float64(0.08585457105482137)), (143, np.float64(0.08787495503274936)), (144, np.float64(0.050734628943184104)), (145, np.float64(0.019510570275964215)), (146, np.float64(0.01643989873053573)), (147, np.float64(0.056388387443460086)), (148, np.float64(0.09863939238321438)), (149, np.float64(0.15719549837837185)), (150, np.float64(0.16646698038757363)), (151, np.float64(0.2056773510573183)), (152, np.float64(0.08458258116519013)), (153, np.float64(0.07974522228289)), (154, np.float64(0.06213697660012)), (155, np.float64(0.020712325533373332)), (156, np.float64(0.06070834938872646)), (157, np.float64(0.10067340828210367)), (158, np.float64(0.13549162565314346)), (159, np.float64(0.0644825880219161)), (160, np.float64(0.11869522585912262)), (161, np.float64(0.03224129401095805)), (162, np.float64(0.03355780276070122)), (163, np.float64(0.05134961659630968)), (164, np.float64(0.08108108108108109)), (165, np.float64(0.04649905549752771)), (166, np.float64(0.12683657235796025)), (167, np.float64(0.09158437663089954)), (168, np.float64(0.17757120130114434)), (169, np.float64(0.08948747402853657)), (170, np.float64(0.10793322294408637)), (171, np.float64(0.02302046277580654)), (172, np.float64(0.21524880100025257)), (173, np.float64(0.02348556961505104)), (174, np.float64(0.07897471897389846)), (175, np.float64(0.07194017065667525)), (176, np.float64(0.029526929767874632)), (177, np.float64(0.0)), (178, np.float64(0.024784079854830485)), (179, np.float64(0.07352146220938077)), (180, np.float64(0.022371868507134143)), (181, np.float64(0.04559607525875532)), (182, np.float64(0.1186447494690624)), (183, np.float64(0.0713262951621492)), (184, np.float64(0.17757120130114434)), (185, np.float64(0.05134961659630968)), (186, np.float64(0.059808916712167495)), (187, np.float64(0.1559625734730109)), (188, np.float64(0.022371868507134143)), (189, np.float64(0.1162476387438193)), (190, np.float64(0.08561170049453902)), (191, np.float64(0.04956815970966097)), (192, np.float64(0.047960113771116836)), (193, np.float64(0.07983920607777244)), (194, np.float64(0.0)), (195, np.float64(0.06003002251876642)), (196, np.float64(0.05264981264926564)), (197, np.float64(0.037470006725398436)), (198, np.float64(0.058123819371909635)), (199, np.float64(0.08787495503274936)), (200, np.float64(0.11028219331407116)), (201, np.float64(0.0)), (202, np.float64(0.03163859985841663)), (203, np.float64(0.08458258116519013)), (204, np.float64(0.050141221056390024)), (205, np.float64(0.07543142864047142)), (206, np.float64(0.11241002017619531)), (207, np.float64(0.07798128673650545)), (208, np.float64(0.12427395320024)), (209, np.float64(0.0685591170191061)), (210, np.float64(0.07610194341477616)), (211, np.float64(0.024784079854830485)), (212, np.float64(0.06711560552140243)), (213, np.float64(0.059808916712167495)), (214, np.float64(0.0)), (215, np.float64(0.06711560552140243)), (216, np.float64(0.06575959492214292)), (217, np.float64(0.0863465783552691)), (218, np.float64(0.03874921291460643)), (219, np.float64(0.09320546490018)), (220, np.float64(0.18009006755629928)), (221, np.float64(0.047960113771116836)), (222, np.float64(0.08094446585163528)), (223, np.float64(0.10529962529853128)), (224, np.float64(0.061649620239508984)), (225, np.float64(0.047457899787624956)), (226, np.float64(0.030528125543633176)), (227, np.float64(0.08336550215650926)), (228, np.float64(0.11185934253567072)), (229, np.float64(0.10892898631973956)), (230, np.float64(0.0930725988812425)), (231, np.float64(0.0)), (232, np.float64(0.11277677488692017)), (233, np.float64(0.10514994558491725)), (234, np.float64(0.08710071126186844)), (235, np.float64(0.07702442489446452)), (236, np.float64(0.11624763874381927)), (237, np.float64(0.06711560552140244)), (238, np.float64(0.11241002017619531)), (239, np.float64(0.09248165577087425)), (240, np.float64(0.047457899787624956)), (241, np.float64(0.08000711205939975)), (242, np.float64(0.08219949365267865)), (243, np.float64(0.09394227846020416)), (244, np.float64(0.09320546490018)), (245, np.float64(0.08219949365267865)), (246, np.float64(0.07696578428840449)), (247, np.float64(0.0)), (248, np.float64(0.04516387521771449)), (249, np.float64(0.14019992744655632)), (250, np.float64(0.0)), (251, np.float64(0.04244763599780088)), (252, np.float64(0.02054987341316966)), (253, np.float64(0.06367145399670132)), (254, np.float64(0.07045670884515312)), (255, np.float64(0.0)), (256, np.float64(0.11314714296070713)), (257, np.float64(0.05405405405405406)), (258, np.float64(0.01793740008335438)), (259, np.float64(0.06213697660012)), (260, np.float64(0.20668850837512243)), (261, np.float64(0.024507154069793594)), (262, np.float64(0.10793322294408637)), (263, np.float64(0.09863939238321438)), (264, np.float64(0.0)), (265, np.float64(0.027788500718836418)), (266, np.float64(0.10028244211278005)), (267, np.float64(0.06575959492214292)), (268, np.float64(0.0533380747062665)), (269, np.float64(0.03001501125938321)), (270, np.float64(0.08948747402853657)), (271, np.float64(0.07194017065667525)), (272, np.float64(0.028194193721730043)), (273, np.float64(0.021402925123634755)), (274, np.float64(0.09097816785925636)), (275, np.float64(0.1453095484297741)), (276, np.float64(0.06327719971683327)), (277, np.float64(0.05381220025006314)), (278, np.float64(0.1186447494690624)), (279, np.float64(0.09394227846020416)), (280, np.float64(0.0)), (281, np.float64(0.06590621627456203)), (282, np.float64(0.04516387521771449)), (283, np.float64(0.027788500718836418)), (284, np.float64(0.0186145197762485)), (285, np.float64(0.01979131233319198)), (286, np.float64(0.07916524933276792)), (287, np.float64(0.02632490632463282)), (288, np.float64(0.027788500718836418)), (289, np.float64(0.04649905549752771)), (290, np.float64(0.06327719971683327)), (291, np.float64(0.050141221056390024)), (292, np.float64(0.09004503377814962)), (293, np.float64(0.03001501125938321)), (294, np.float64(0.1453095484297741)), (295, np.float64(0.106676149412533)), (296, np.float64(0.03929887459459296)), (297, np.float64(0.04474373701426829)), (298, np.float64(0.0)), (299, np.float64(0.06025359879550432)), (300, np.float64(0.17348855898381338)), (301, np.float64(0.09491579957524988)), (302, np.float64(0.07045670884515312)), (303, np.float64(0.028194193721730043)), (304, np.float64(0.06667259338283313)), (305, np.float64(0.1926263261127128)), (306, np.float64(0.08219949365267865)), (307, np.float64(0.11022596991336672)), (308, np.float64(0.0685591170191061)), (309, np.float64(0.06327719971683327)), (310, np.float64(0.03106848830006)), (311, np.float64(0.1522038868295523)), (312, np.float64(0.10146925788636821)), (313, np.float64(0.055577001437672836)), (314, np.float64(0.0)), (315, np.float64(0.08458258116519013)), (316, np.float64(0.0)), (317, np.float64(0.0)), (318, np.float64(0.0)), (319, np.float64(0.10067340828210367)), (320, np.float64(0.03106848830006)), (321, np.float64(0.0)), (322, np.float64(0.213352298825066)), (323, np.float64(0.03001501125938321)), (324, np.float64(0.024507154069793594)), (325, np.float64(0.10067340828210367)), (326, np.float64(0.05723638070321425)), (327, np.float64(0.027788500718836418)), (328, np.float64(0.027788500718836418)), (329, np.float64(0.08000711205939975)), (330, np.float64(0.10146925788636821)), (331, np.float64(0.09119215051751065)), (332, np.float64(0.10810810810810811)), (333, np.float64(0.024784079854830485)), (334, np.float64(0.09802861627917438)), (335, np.float64(0.04697113923010208)), (336, np.float64(0.07009996372327816)), (337, np.float64(0.04604092555161308)), (338, np.float64(0.0)), (339, np.float64(0.04956815970966097)), (340, np.float64(0.050141221056390024)), (341, np.float64(0.08336550215650926)), (342, np.float64(0.1633934794796094)), (343, np.float64(0.019510570275964215)), (344, np.float64(0.03001501125938321)), (345, np.float64(0.023249527748763855)), (346, np.float64(0.0)), (347, np.float64(0.0)), (348, np.float64(0.06213697660012)), (349, np.float64(0.07702442489446452)), (350, np.float64(0.04956815970966097)), (351, np.float64(0.0)), (352, np.float64(0.027788500718836418)), (353, np.float64(0.041757384532966166)), (354, np.float64(0.02196873875818734)), (355, np.float64(0.036992662308349696)), (356, np.float64(0.09158437663089952)), (357, np.float64(0.0)), (358, np.float64(0.06105625108726635)), (359, np.float64(0.03163859985841663)), (360, np.float64(0.02122381799890044)), (361, np.float64(0.07610194341477616)), (362, np.float64(0.09672388203287416)), (363, np.float64(0.10042266465917388)), (364, np.float64(0.023728949893812478)), (365, np.float64(0.07610194341477616)), (366, np.float64(0.05723638070321425)), (367, np.float64(0.0)), (368, np.float64(0.13151918984428584)), (369, np.float64(0.08108108108108109)), (370, np.float64(0.05134961659630968)), (371, np.float64(0.09695723311274393)), (372, np.float64(0.047960113771116836)), (373, np.float64(0.1752499093081954)), (374, np.float64(0.038482892144202245)), (375, np.float64(0.06213697660011999)), (376, np.float64(0.047457899787624956)), (377, np.float64(0.0)), (378, np.float64(0.0)), (379, np.float64(0.05141933776432957)), (380, np.float64(0.05264981264926564)), (381, np.float64(0.08489527199560176)), (382, np.float64(0.0)), (383, np.float64(0.04393747751637468)), (384, np.float64(0.029061909685954818)), (385, np.float64(0.0)), (386, np.float64(0.022167554926073633)), (387, np.float64(0.023980056885558418)), (388, np.float64(0.0)), (389, np.float64(0.0885807893036239)), (390, np.float64(0.02666903735313325)), (391, np.float64(0.05733298225836872)), (392, np.float64(0.030528125543633176)), (393, np.float64(0.0)), (394, np.float64(0.025070610528195012)), (395, np.float64(0.05264981264926564)), (396, np.float64(0.04433510985214727)), (397, np.float64(0.05264981264926564)), (398, np.float64(0.0)), (399, np.float64(0.023980056885558418)), (400, np.float64(0.09158437663089952)), (401, np.float64(0.03106848830006)), (402, np.float64(0.07897471897389846)), (403, np.float64(0.08419653359482289)), (404, np.float64(0.06213697660012)), (405, np.float64(0.056388387443460086)), (406, np.float64(0.021049133398705722)), (407, np.float64(0.021586644588817275)), (408, np.float64(0.03287979746107146)), (409, np.float64(0.0)), (410, np.float64(0.09913631941932194)), (411, np.float64(0.0533380747062665)), (412, np.float64(0.09695723311274393)), (413, np.float64(0.14309095175803563)), (414, np.float64(0.03001501125938321)), (415, np.float64(0.05413539955388112)), (416, np.float64(0.05134961659630968)), (417, np.float64(0.03287979746107146)), (418, np.float64(0.03587480016670876)), (419, np.float64(0.06974858324629157)), (420, np.float64(0.1139901881468883)), (421, np.float64(0.02348556961505104)), (422, np.float64(0.11810771907149853)), (423, np.float64(0.041757384532966166)), (424, np.float64(0.037470006725398436)), (425, np.float64(0.06475993376645182)), (426, np.float64(0.05446449315986979)), (427, np.float64(0.02666903735313325)), (428, np.float64(0.056573571480353566)), (429, np.float64(0.0)), (430, np.float64(0.05134961659630968)), (431, np.float64(0.024507154069793594)), (432, np.float64(0.11510231387903269)), (433, np.float64(0.03163859985841663)), (434, np.float64(0.0)), (435, np.float64(0.03587480016670876)), (436, np.float64(0.0)), (437, np.float64(0.025993762245501817)), (438, np.float64(0.12392039927415242)), (439, np.float64(0.02666903735313325)), (440, np.float64(0.025070610528195012)), (441, np.float64(0.058123819371909635)), (442, np.float64(0.04604092555161308)), (443, np.float64(0.06475993376645182)), (444, np.float64(0.0)), (445, np.float64(0.10028244211278005)), (446, np.float64(0.02348556961505104)), (447, np.float64(0.06532553344640132)), (448, np.float64(0.021586644588817275)), (449, np.float64(0.11115400287534567)), (450, np.float64(0.021586644588817275)), (451, np.float64(0.025367314471592052)), (452, np.float64(0.03106848830006)), (453, np.float64(0.024784079854830485)), (454, np.float64(0.11742784807525519)), (455, np.float64(0.061649620239508984)), (456, np.float64(0.04393747751637468)), (457, np.float64(0.08718572905786445)), (458, np.float64(0.04393747751637468)), (459, np.float64(0.03504998186163908)), (460, np.float64(0.024507154069793594)), (461, np.float64(0.14309095175803563)), (462, np.float64(0.03271662128033808)), (463, np.float64(0.03287979746107146)), (464, np.float64(0.0)), (465, np.float64(0.0)), (466, np.float64(0.14704292441876154)), (467, np.float64(0.10701462561817378)), (468, np.float64(0.028194193721730043)), (469, np.float64(0.06025359879550432)), (470, np.float64(0.04604092555161308)), (471, np.float64(0.06475993376645182)), (472, np.float64(0.10810810810810811)), (473, np.float64(0.09394227846020416)), (474, np.float64(0.0)), (475, np.float64(0.04433510985214727)), (476, np.float64(0.1371182340382122)), (477, np.float64(0.0)), (478, np.float64(0.05479966243511909)), (479, np.float64(0.0891578689526865)), (480, np.float64(0.09913631941932194)), (481, np.float64(0.0)), (482, np.float64(0.022167554926073633)), (483, np.float64(0.12655439943366653)), (484, np.float64(0.029526929767874632)), (485, np.float64(0.0533380747062665)), (486, np.float64(0.08099356774626426)), (487, np.float64(0.1289651760438322)), (488, np.float64(0.06746792083200746)), (489, np.float64(0.0)), (490, np.float64(0.14349920066683505)), (491, np.float64(0.10042266465917388)), (492, np.float64(0.07702442489446452)), (493, np.float64(0.03106848830006)), (494, np.float64(0.0)), (495, np.float64(0.19344776406574832)), (496, np.float64(0.0)), (497, np.float64(0.0)), (498, np.float64(0.0685591170191061)), (499, np.float64(0.0)), (500, np.float64(0.02632490632463282)), (501, np.float64(0.08284930213349333)), (502, np.float64(0.13549162565314346)), (503, np.float64(0.07610194341477615)), (504, np.float64(0.0)), (505, np.float64(0.1371182340382122)), (506, np.float64(0.03504998186163908)), (507, np.float64(0.25903973506580724)), (508, np.float64(0.10269923319261937)), (509, np.float64(0.022371868507134143)), (510, np.float64(0.10028244211278005)), (511, np.float64(0.09320546490018)), (512, np.float64(0.027788500718836418)), (513, np.float64(0.15042366316917008)), (514, np.float64(0.050141221056390024)), (515, np.float64(0.025070610528195012)), (516, np.float64(0.028618190351607124)), (517, np.float64(0.0)), (518, np.float64(0.04433510985214727)), (519, np.float64(0.0)), (520, np.float64(0.0)), (521, np.float64(0.025367314471592052)), (522, np.float64(0.024507154069793594)), (523, np.float64(0.04901430813958719)), (524, np.float

In [38]:
movie_list[:10]

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.08458258116519013)),
 (2, np.float64(0.08718572905786445)),
 (3, np.float64(0.074458079104994)),
 (4, np.float64(0.19184045508446734)),
 (5, np.float64(0.1098436937909367)),
 (6, np.float64(0.04078236951430929)),
 (7, np.float64(0.1487044791289829)),
 (8, np.float64(0.06003002251876642)),
 (9, np.float64(0.09802861627917438))]

In [39]:
movie_list = sorted(
    movie_list,
    key=lambda x:x[1],
    reverse=True
)

In [40]:
movie_list[:10]

[(0, np.float64(0.9999999999999998)),
 (1213, np.float64(0.29061909685954823)),
 (2403, np.float64(0.2726248784031354)),
 (3723, np.float64(0.26401000024165)),
 (507, np.float64(0.25903973506580724)),
 (539, np.float64(0.2537477434955704)),
 (582, np.float64(0.2484013136974297)),
 (1201, np.float64(0.24784079854830487)),
 (1191, np.float64(0.23995690956687135)),
 (61, np.float64(0.23490461932490855))]

In [41]:
movie_list[1:6] # skip 1st

[(1213, np.float64(0.29061909685954823)),
 (2403, np.float64(0.2726248784031354)),
 (3723, np.float64(0.26401000024165)),
 (507, np.float64(0.25903973506580724)),
 (539, np.float64(0.2537477434955704))]

In [43]:
movies.iloc[movie_index].title

'Avatar'

In [46]:
def recommend(movie):
      
    # Step 1
    movie_index = movies[movies["title"] == movie].index[0]
    
    # Step 2
    distances = similarity[movie_index]

    # Step 3
    movie_list = sorted(
        list(enumerate(distances)),
        key=lambda x: x[1],
        reverse=True
    )
    # Step 4
    recommended_movies = []
    # Step 5
    for i in movie_list[1:6]:
        recommended_movies.append(movies.iloc[i[0]].title)

    return recommended_movies

In [51]:
recommend("Pirates of the Caribbean: At World's End")

["Pirates of the Caribbean: Dead Man's Chest",
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'Pirates of the Caribbean: On Stranger Tides',
 'Life of Pi',
 '20,000 Leagues Under the Sea']

In [52]:
import pickle

In [54]:
pickle.dump(
    movies,
    open("/100_Days_of_ml/Hybrid_Movie_Recommendation_System/models/movies.pkl","wb")
)

In [55]:
pickle.dump(
    similarity,
    open("/100_Days_of_ml/Hybrid_Movie_Recommendation_System/models/similarity.pkl","wb")
)